services:
  dev-env:
    build:
      context: .
      args:
        - BUILD_DATE=${BUILD_DATE:-}
    container_name: dev-environment
    env_file:
      - .env
    user: "1000:1000"
    init: true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
      - SYS_CHROOT
    read_only: false
    security_opt:
      - no-new-privileges:false
    ports:
      - "2222:2222"
      - "8080:8080"
      - "3000:3000"
      - "9000:9000"
    volumes:
      - ./workspace:/workspace
      - ./configs/.vimrc:/home/dev/.vimrc:ro
      - ./configs/.zshrc:/home/dev/.zshrc:ro
      - ./configs/.bashrc:/home/dev/.bashrc:ro
      - ./configs/.tmux.conf:/home/dev/.tmux.conf:ro
      - ./configs/linux/etc/sysctl.d/99-custom.conf:/etc/sysctl.d/99-custom.conf:ro
      - ./configs/linux/etc/profile.d/99-custom.sh:/etc/profile.d/99-custom.sh:ro
      - ./configs/linux/etc/sysctl.d/99-network.conf:/etc/sysctl.d/99-network.conf:ro
      - security-tools:/home/dev/.security
      - go-cache:/home/dev/go
      - shell-history:/home/dev/.shell_history
      - git-tools:/home/dev/.git_tools
      - aws-config:/home/dev/.aws
      - vscode-config:/home/dev/.vscode-server
      - npm-cache:/home/dev/.npm
      - /var/run/docker.sock:/var/run/docker.sock
      - docker-config:/home/dev/.docker
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - dev-network

volumes:
  go-cache:
  shell-history:
  git-tools:
  security-tools:
  aws-config:
  vscode-config:
  npm-cache:
  docker-config:

networks:
  dev-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16