services:
  dev-env:
    build:
      context: .
      args:
        - BUILD_DATE=${BUILD_DATE:-}
    container_name: dev-environment
    ports:
      - "2222:22"
      - "8080:8080"
      - "3000:3000"
      - "9000:9000"
    volumes:
      - ./workspace:/workspace
      - ./configs/.vimrc:/home/dev/.vimrc:ro
      - ./configs/.zshrc:/home/dev/.zshrc:ro
      - ./configs/.tmux.conf:/home/dev/.tmux.conf:ro
      - ssh-config:/home/dev/.ssh
      - go-cache:/home/dev/go
      - zsh-history:/home/dev/.zsh_history_data
      - bash-history:/home/dev/.bash_history_data
      - gh-config:/home/dev/.config/gh
      - aws-config:/home/dev/.aws
      - git-credentials:/home/dev/.git-credentials-dir
      - gnupg-config:/home/dev/.gnupg
      - git-config:/home/dev/.git-config-volume
      - /var/run/docker.sock:/var/run/docker.sock
      - docker-config:/home/dev/.docker
    environment:
      - GOPROXY=https://proxy.golang.org,direct
      - GOSUMDB=sum.golang.org
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  go-cache:
  zsh-history:
  bash-history:
  gh-config:
  aws-config:
  git-credentials:
  gnupg-config:
  git-config:
  ssh-config:
  docker-config:
