services:
  dev-env:
    build:
      context: .
      args:
        - BUILD_DATE=${BUILD_DATE:-}
    container_name: dev-environment
    ports:
      - "2222:22"
      - "8080:8080"
      - "3000:3000"
      - "9000:9000"
    volumes:
      - ./workspace:/workspace
      - ./configs/.vimrc:/home/dev/.vimrc:ro
      - ./configs/.zshrc:/home/dev/.zshrc:ro
      - ./configs/.bashrc:/home/dev/.bashrc:ro
      - ./configs/.tmux.conf:/home/dev/.tmux.conf:ro
      - security-tools:/home/dev/.security
      - go-cache:/home/dev/go
      - shell-history:/home/dev/.shell_history
      - git-tools:/home/dev/.git_tools
      - aws-config:/home/dev/.aws
      - /var/run/docker.sock:/var/run/docker.sock
      - docker-config:/home/dev/.docker
    environment:
      - GOPROXY=https://proxy.golang.org,direct
      - GOSUMDB=sum.golang.org
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  go-cache:
  shell-history:
  git-tools:
  security-tools:
  aws-config:
  docker-config:
